server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  info:
    title: My REST API
    description: API for managing users
    version: 1.0
    contact:
      name: John Doe
      url: https://example.com
      email: john.doe@example.com

logging:
  level:
    org.springframework.security: trace

